In [21]:
import pandas as pd
import numpy as np
import normalization
import importlib
importlib.reload(normalization)

In [22]:
lines = []
with open('nouns.txt', 'r') as nouns:
    for x in nouns:
        new_line = x.split('\t')
        if len(new_line) > 1:
            new_line[2] = new_line[2][:-1]
            lines.append(new_line)

In [23]:
normalized_lines = normalization.normalize_data(lines)

In [24]:
cleansed_lines = normalization.purge_pure_duplicates(normalized_lines)

In [25]:
chassis = pd.read_csv('nouns.csv')

/tmp/ipykernel_49769/774707866.py:1: DtypeWarning: Columns (5,6,8,11,12,20,21,29,30,38,39,47,48,56,57,65,66,74,75) have mixed types. Specify dtype option on import or set low_memory=False.
  chassis = pd.read_csv('nouns.csv')

In [26]:
chassis.columns

Index(['lemma', 'pos', 'genus', 'genus 1', 'genus 2', 'genus 3', 'genus 4',
       'nominativ singular', 'nominativ singular*', 'nominativ singular 1',
       'nominativ singular 2', 'nominativ singular 3', 'nominativ singular 4',
       'nominativ singular stark', 'nominativ singular schwach',
       'nominativ singular gemischt', 'nominativ plural', 'nominativ plural*',
       'nominativ plural 1', 'nominativ plural 2', 'nominativ plural 3',
       'nominativ plural 4', 'nominativ plural stark',
       'nominativ plural schwach', 'nominativ plural gemischt',
       'genitiv singular', 'genitiv singular*', 'genitiv singular 1',
       'genitiv singular 2', 'genitiv singular 3', 'genitiv singular 4',
       'genitiv singular stark', 'genitiv singular schwach',
       'genitiv singular gemischt', 'genitiv plural', 'genitiv plural*',
       'genitiv plural 1', 'genitiv plural 2', 'genitiv plural 3',
       'genitiv plural 4', 'genitiv plural stark', 'genitiv plural schwach',
       'genitiv plural gemischt', 'dativ singular', 'dativ singular*',
       'dativ singular 1', 'dativ singular 2', 'dativ singular 3',
       'dativ singular 4', 'dativ singular stark', 'dativ singular schwach',
       'dativ singular gemischt', 'dativ plural', 'dativ plural*',
       'dativ plural 1', 'dativ plural 2', 'dativ plural 3', 'dativ plural 4',
       'dativ plural stark', 'dativ plural schwach', 'dativ plural gemischt',
       'akkusativ singular', 'akkusativ singular*', 'akkusativ singular 1',
       'akkusativ singular 2', 'akkusativ singular 3', 'akkusativ singular 4',
       'akkusativ singular stark', 'akkusativ singular schwach',
       'akkusativ singular gemischt', 'akkusativ plural', 'akkusativ plural*',
       'akkusativ plural 1', 'akkusativ plural 2', 'akkusativ plural 3',
       'akkusativ plural 4', 'akkusativ plural stark',
       'akkusativ plural schwach', 'akkusativ plural gemischt'],
      dtype='object')

In [32]:
cleansed_lines = sorted(cleansed_lines, key=lambda x: x[2])
print(cleansed_lines)

[['170.', 'Dinner', 'Das Abendessen', 'Die Abendessen'], ['1286.', 'Adventure', 'Das Abenteuer', 'Die Abenteuer'], ['1773.', 'Compartment', 'Das Abteil', 'Die Abteile'], ['2086.', 'Badge', 'Das Abzeichen', 'Die Abzeichen'], ['1698.', 'Shrug', 'Das Achselzucken', '-'], ['2668.', 'Gentry', 'Das Adel', '-'], ['2153.', 'Album', 'Das Album', 'Die Alben'], ['743.', 'Alien', 'Das Alien', 'Die Aliens'], ['173.', 'Age', 'Das Alter', '-'], ['2420.', 'Aluminum', 'Das Aluminium', '-'], ['1175.', 'Offer', 'Das Angebot', 'Die Angebote'], ['1118.', 'Fishing', 'Das Angeln', '-'], ['2211.', 'Dressing', 'Das Ankleiden', '-'], ['2834.', 'Swell', 'Das Anschwellen', 'Die Anschwellen'], ['1082.', 'Estate', 'Das Anwesen', 'Die Anwesen'], ['936.', 'Argument', 'Das Argument', 'Die Argumente'], ['2142.', 'Bracelet', 'Das Armband', 'Die Armbänder'], ['2864.', 'Aroma', 'Das Aroma', 'Die Aromen'], ['2568.', 'Array', 'Das Array', 'Die Arrays'], ['1505.', 'Asshole', 'Das Arschloch', 'Die Arschlöcher'], ['2364.', 'Artifact', 'Das Artefakt', 'Die Artefakte'], ['1138.', 'Ace', 'Das Ass', 'Die Asse'], ['949.', 'Breathing', 'Das Atmen', '-'], ['2873.', 'Auditorium', 'Das Auditorium', 'Die Auditorien'], ['2975.', 'Glint', 'Das Aufblitzen', 'Die Aufblitzen'], ['1933.', 'Encounter', 'Das Aufeinandertreffen', 'Die Aufeinandertreffen'], ['6.', 'Eye', 'Das Auge', 'Die Augen'], ['1733.', 'Eyelid', 'Das Augenlid', 'Die Augenlider'], ['868.', 'Appearance', 'Das Aussehen', '-'], ['25.', 'Car', 'Das Auto', 'Die Autos'], ['81.', 'Baby', 'Das Baby', 'Die Babys'], ['2851.', 'Backup', 'Das Backup', 'Die Backups'], ['1054.', 'Bath', 'Das Bad', 'Die Bäder'], ['287.', 'Bathroom', 'Das Badezimmer', 'Die Badezimmer'], ['2306.', 'Canopy', 'Das Baldachin', 'Die Baldachine'], ['529.', 'Tape', 'Das Band', 'Die Bänder'], ['2148.', 'Banner', 'Das Banner', 'Die Banner'], ['882.', 'Cash', 'Das Bargeld', '-'], ['2534.', 'Farmhouse', 'Das Bauernhaus', 'Die Bauernhäuser'], ['2460.', 'Basin', 'Das Becken', 'Die Becken'], ['1962.', 'Regret', 'Das Bedauern', '-'], ['375.', 'Need', 'Das Bedürfnis', 'Die Bedürfnisse'], ['74.', 'Leg', 'Das Bein', 'Die Beine'], ['1509.', 'Example', 'Das Beispiel', 'Die Beispiele'], ['2028.', 'Amber', 'Das Bernstein', '-'], ['42.', 'Bed', 'Das Bett', 'Die Betten'], ['1541.', 'Consciousness', 'Das Bewusstsein', '-'], ['303.', 'Beer', 'Das Bier', 'Die Biere'], ['131.', 'Picture', 'Das Bild', 'Die Bilder'], ['258.', 'Bit', 'Das Bit', 'Die Bits'], ['348.', 'Leaf', 'Das Blatt', 'Die Blätter'], ['1062.', 'Blue', 'Das Blau', '-'], ['997.', 'Lead', 'Das Blei', '-'], ['1583.', 'Glare', 'Das Blenden', '-'], ['102.', 'Blood', 'Das Blut', '-'], ['2694.', 'Petal', 'Das Blütenblatt', 'Die Blütenblätter'], ['255.', 'Boat', 'Das Boot', 'Die Boote'], ['2644.', 'Fry', 'Das Braten', 'Die Braten'], ['1340.', 'Brown', 'Das Braun', '-'], ['423.', 'Board', 'Das Brett', 'Die Bretter'], ['601.', 'Bread', 'Das Brot', '-'], ['2246.', 'Hum', 'Das Brummen', '-'], ['1922.', 'Patty', 'Das Brötchen', 'Die Brötchen'], ['61.', 'Book', 'Das Buch', 'Die Bücher'], ['1266.', 'Evil', 'Das Böse', '-'], ['1630.', 'Bundle', 'Das Bündel', 'Die Bündel'], ['76.', 'Office', 'Das Büro', 'Die Büros'], ['1585.', 'Cafe', 'Das Café', 'Die Cafés'], ['1553.', 'Chaos', 'Das Chaos', '-'], ['2263.', 'Chili', 'Das Chili', 'Die Chilis'], ['2463.', 'Cockpit', 'Das Cockpit', 'Die Cockpits'], ['296.', 'College', 'Das College', 'Die Colleges'], ['2776.', 'Corps', 'Das Corps', 'Die Cores'], ['361.', 'Roof', 'Das Dach', 'Die Dächer'], ['2617.', 'Loan', 'Das Darlehen', 'Die Darlehen'], ['475.', 'Date', 'Das Datum', 'Die Daten'], ['491.', 'Deck', 'Das Deck', 'Die Decks'], ['669.', 'Thinking', 'Das Denken', '-'], ['2325.', 'Memorial', 'Das Denkmal', 'Die Denkmäler'], ['1117.', 'Design', 'Das Design', 'Die Designs'], ['2179.', 'Dessert', 'Das Dessert', 'Die Desserts'], ['441.', 'Detail', 'Das Detail', 'Die Details'], ['1982.', 'Chart', 'Das Diagramm', 'Die Diagramme'], ['1440.', 'Document', 'Das Dokument', 'Die Dokumente'], ['2656.', 'Double', 'Das Doppel', 'Die Dopple'], ['332.', 'Village', 'Das Dorf', 'Die Dörfer'], ['1980.', 'Drama', 'Das Drama', 'Die Dramen'], ['2565.', 'Triangle', 'Das Dreieck', 'Die Dreiecke'], ['747.', 'Mess', 'Das Durcheinander', '-'], ['1276.', 'Jet', 'Das Düsenflugzeug', 'Die Düsenflugzeuge'], ['1722.', 'Echo', 'Das Echo', 'Die Echos'], ['2764.', 'Ego', 'Das Ego', 'Die Egos'], ['2262.', 'Awe', 'Das Ehrfurcht', '-'], ['437.', 'Egg', 'Das Ei', 'Die Eier'], ['1892.', 'Squirrel', 'Das Eichhörnchen', 'Die Eichhörnchen'], ['847.', 'Property', 'Das Eigentum', '-'], ['2737.', 'Freeze', 'Das Einfrieren', 'Die Einfrierungen'], ['1408.', 'Mall', 'Das Einkaufszentrum', 'Die Einkaufszentren'], ['2450.', 'Income', 'Das Einkommen', 'Die Einkommen'], ['244.', 'Ice', 'Das Eis', 'Die Eis'], ['580.', 'Iron', 'Das Eisen', 'Die Eisen'], ['1396.', 'Element', 'Das Element', 'Die Elemente'], ['1941.', 'Misery', 'Das Elend', '-'], ['2292.', 'Ivory', 'Das Elfenbein', '-'], ['49.', 'End', 'Das Ende', 'Die Enden'], ['2527.', 'Engagement', 'Das Engagement', 'Die Engagements'], ['590.', 'English', 'Das Englisch', '-'], ['2183.', 'Grandchild', 'Das Enkelkind', 'Die Enkelkinder'], ['2687.', 'Dismay', 'Das Entsetzen', '-'], ['2892.', 'Earthquake', 'Das Erdbeben', 'Die Erdbeben'], ['418.', 'Event', 'Das Ereignis', 'Die Ereignisse'], ['688.', 'Result', 'Das Ergebnis', 'Die Ergebnisse'], ['2257.', 'Amazement', 'Das Erstaunen', '-'], ['1947.', 'Wake', 'Das Erwachen', 'Die Erwachen'], ['144.', 'Food', 'Das Essen', '-'], ['783.', 'Dining', 'Das Esszimmer', '-'], ['2113.', 'Label', 'Das Etikett', 'Die Etiketten'], ['761.', 'Copy', 'Das Exemplar', 'Die Exemplare'], ['476.', 'Subject', 'Das Fach', 'Die Fächer'], ['967.', 'Bike', 'Das Fahrrad', 'Die Fahrräder'], ['778.', 'Vehicle', 'Das Fahrzeug', 'Die Fahrzeuge'], ['1041.', 'Barrel', 'Das Fass', 'Die Fässer'], ['2684.', 'Hiss', 'Das Fauchen', 'Die Fauchen'], ['146.', 'Field', 'Das Feld', 'Die Felder'], ['38.', 'Window', 'Das Fenster', 'Die Fenster'], ['2445.', 'Binoculars', 'Das Fernglas', 'Die Ferngläser'], ['2627.', 'Festival', 'Das Festival', 'Die Festivals'], ['2270.', 'Feast', 'Das Festmahl', 'Die Festmahle'], ['1257.', 'Fat', 'Das Fett', 'Die Fette'], ['100.', 'Fire', 'Das Feuer', 'Die Feuer'], ['2490.', 'Lighter', 'Das Feuerzeug', 'Die Feuerzeuge'], ['1554.', 'Fever', 'Das Fieber', '-'], ['2659.', 'Finish', 'Das Finish', 'Die Finish'], ['1494.', 'Gym', 'Das Fitnessstudio', 'Die Fitnessstudios'], ['2634.', 'Flicker', 'Das Flackern', 'Die Flackern'], ['2965.', 'Flannel', 'Das Flanell', 'Die Flanell'], ['457.', 'Flesh', 'Das Fleisch', '-'], ['2840.', 'Flying', 'Das Fliegen', '-'], ['2453.', 'Raft', 'Das Floß', 'Die Floße'], ['393.', 'Plane', 'Das Flugzeug', 'Die Flugzeuge'], ['893.', 'Whisper', 'Das Flüstern', 'Die Flüster'], ['1498.', 'Fort', 'Das Fort', 'Die Forts'], ['412.', 'Photo', 'Das Foto', 'Die Fotos'], ['2089.', 'Foyer', 'Das Foyer', 'Die Foyers'], ['1935.', 'Fragment', 'Das Fragment', 'Die Fragmente'], ['501.', 'Breakfast', 'Das Frühstück', 'Die Frühstücke'], ['2087.', 'Fund', 'Das Fundament', 'Die Fundamente'], ['2623.', 'Feed', 'Das Futter', '-'], ['1338.', 'Whole', 'Das Ganze', '-'], ['505.', 'Gas', 'Das Gas', '-'], ['671.', 'Prayer', 'Das Gebet', 'Die Gebete'], ['242.', 'Area', 'Das Gebiet', 'Die Gebiete'], ['1457.', 'Roar', 'Das Gebrüll', '-'], ['107.', 'Building', 'Das Gebäude', 'Die Gebäude'], ['2234.', 'Complex', 'Das Gebäudekomplex', 'Die Gebäudekomplexe'], ['707.', 'Poem', 'Das Gedicht', 'Die Gedichte'], ['737.', 'Prison', 'Das Gefängnis', 'Die Gefängnisse'], ['1418.', 'Vessel', 'Das Gefäß', 'Die Gefäße'], ['206.', 'Feeling', 'Das Gefühl', 'Die Gefühle'], ['2600.', 'Salary', 'Das Gehalt', 'Die Gehälter'], ['467.', 'Secret', 'Das Geheimnis', 'Die Geheimnisse'], ['1048.', 'Walking', 'Das Gehen', '-'], ['322.', 'Brain', 'Das Gehirn', 'Die Gehirne'], ['71.', 'Money', 'Das Geld', '-'], ['1801.', 'Knuckle', 'Das Gelenk', 'Die Gelenke'], ['2868.', 'Terrain', 'Das Gelände', 'Die Gelände'], ['1549.', 'Railing', 'Das Geländer', 'Die Geländer'], ['2897.', 'Vow', 'Das Gelübde', 'Die Gelübde'], ['558.', 'Painting', 'Das Gemälde', 'Die Gemälde'], ['1356.', 'Vegetable', 'Das Gemüse', 'Die Gemüse'], ['1481.', 'Gene', 'Das Gen', 'Die Gene'], ['1619.', 'Genius', 'Das Genie', 'Die Genies'], ['2305.', 'Luggage', 'Das Gepäck', '-'], ['434.', 'Court', 'Das Gericht', 'Die Gerichte'], ['2795.', 'Courthouse', 'Das Gerichtsgebäude', 'Die Gerichtsgebäude'], ['1135.', 'Device', 'Das Gerät', 'Die Geräte'], ['308.', 'Noise', 'Das Geräusch', 'Die Geräusche'], ['1283.', 'Rumor', 'Das Gerücht', 'Die Gerüchte'], ['421.', 'Gift', 'Das Geschenk', 'Die Geschenke'], ['2936.', 'Harness', 'Das Geschirr', 'Die Geschirre'], ['2759.', 'Sibling', 'Das Geschwister', 'Die Geschwister'], ['118.', 'Business', 'Das Geschäft', 'Die Geschäfte'], ['335.', 'Law', 'Das Gesetz', 'Die Gesetze'], ['13.', 'Face', 'Das Gesicht', 'Die Gesichter'], ['254.', 'Conversation', 'Das Gespräch', 'Die Gespräche'], ['2177.', 'Confession', 'Das Geständnis', 'Die Geständnisse'], ['2459.', 'Cereal', 'Das Getreide', '-'], ['946.', 'Gear', 'Das Getriebe', 'Die Getriebe'], ['266.', 'Drink', 'Das Getränk', 'Die Getränke'], ['1185.', 'Gown', 'Das Gewand', 'Die Gewänder'], ['1518.', 'Tissue', 'Das Gewebe', 'Die Gewebe'], ['772.', 'Rifle', 'Das Gewehr', 'Die Gewehre'], ['362.', 'Weight', 'Das Gewicht', 'Die Gewichte'], ['2436.', 'Tangle', 'Das Gewirr', 'Die Gewirre'], ['2288.', 'Conscience', 'Das Gewissen', 'Die Gewissen'], ['2509.', 'Vault', 'Das Gewölbe', 'Die Gewölbe'], ['2790.', 'Spice', 'Das Gewürz', 'Die Gewürze'], ['1785.', 'Poison', 'Das Gift', 'Die Gifte'], ['65.', 'Glass', 'Das Glas', 'Die Gläser'], ['1049.', 'Balance', 'Das Gleichgewicht', '-'], ['898.', 'Limb', 'Das Glied', 'Die Glieder'], ['503.', 'Luck', 'Das Glück', '-'], ['274.', 'Gold', 'Das Gold', '-'], ['781.', 'Grave', 'Das Grab', 'Die Gräber'], ['318.', 'Grass', 'Das Gras', 'Die Gräser'], ['1755.', 'Gray', 'Das Grau', '-'], ['615.', 'Grin', 'Das Grinsen', '-'], ['2856.', 'Rumble', 'Das Grollen', 'Die Grollen'], ['87.', 'Lot', 'Das Grundstück', 'Die Grundstücke'], ['1952.', 'Grunt', 'Das Grunzen', 'Die Grunzen'], ['544.', 'Green', 'Das Grün', '-'], ['1391.', 'Good', 'Das Gute', '-'], ['1927.', 'Daisy', 'Das Gänseblümchen', 'Die Gänseblümchen'], ['31.', 'Hair', 'Das Haar', 'Die Haare'], ['636.', 'Hold', 'Das Halten', 'Die Halten'], ['530.', 'Wrist', 'Das Handgelenk', 'Die Handgelenke'], ['672.', 'Towel', 'Das Handtuch', 'Die Handtücher'], ['1664.', 'Craft', 'Das Handwerk', 'Die Handwerke'], ['2076.', 'Headquarters', 'Das Hauptquartier', 'Die Hauptquartiere'], ['17.', 'House', 'Das Haus', 'Die Häuser'], ['1362.', 'Pet', 'Das Haustier', 'Die Haustiere'], ['1371.', 'Rear', 'Das Heck', '-'], ['183.', 'Shirt', 'Das Hemd', 'Die Hemden'], ['2909.', 'Manor', 'Das Herrenhaus', 'Die Herrenhäuser'], ['70.', 'Heart', 'Das Herz', 'Die Herzen'], ['2007.', 'Hay', 'Das Heu', '-'], ['2810.', 'Howl', 'Das Heulen', 'Die Heulungen'], ['2828.', 'Limp', 'Das Hinken', 'Die Hinken'], ['182.', 'Wood', 'Das Holz', '-'], ['903.', 'Horn', 'Das Horn', 'Die Hörner'], ['267.', 'Hotel', 'Das Hotel', 'Die Hotels'], ['527.', 'Chicken', 'Das Huhn', 'Die Hühner'], ['1587.', 'Pounding', 'Das Hämmern', '-'], ['2314.', 'Bunny', 'Das Häschen', 'Die Häschen'], ['1811.', 'Empire', 'Das Imperium', 'Die Reiche'], ['1763.', 'Individual', 'Das Individuum', 'Die Individuen'], ['2329.', 'Engineering', 'Das Ingenieurwesen', '-'], ['994.', 'Inside', 'Das Innere', '-'], ['1477.', 'Insect', 'Das Insekt', 'Die Insekten'], ['2132.', 'Institute', 'Das Institut', 'Die Institute'], ['1167.', 'Instrument', 'Das Instrument', 'Die Instrumente'], ['380.', 'Interest', 'Das Interesse', '-'], ['2462.', 'Internet', 'Das Internet', '-'], ['2661.', 'Interval', 'Das Intervall', 'Die Intervalle'], ['1150.', 'Interview', 'Das Interview', 'Die Interviews'], ['9.', 'Year', 'Das Jahr', 'Die Jahre'], ['512.', 'Century', 'Das Jahrhundert', 'Die Jahrhunderte'], ['944.', 'Decade', 'Das Jahrzehnt', 'Die Jahrzehnte'], ['1379.', 'Journal', 'Das Journal', 'Die Journale'], ['2444.', 'Anniversary', 'Das Jubiläum', 'Die Jubiläen'], ['1904.', 'Jewel', 'Das Juwel', 'Die Juwelen'], ['631.', 'Wire', 'Das Kabel', 'Die Kabel'], ['1679.', 'Calf', 'Das Kalb', 'Die Kälber'], ['2456.', 'Camel', 'Das Kamel', 'Die Kamele'], ['975.', 'Rabbit', 'Das Kaninchen', 'Die Kaninchen'], ['2816.', 'Canoe', 'Das Kanu', 'Die Kanus'], ['1625.', 'Cape', 'Das Kap', 'Die Kaps'], ['987.', 'Chapter', 'Das Kapitel', 'Die Kapitel'], ['2271.', 'Casino', 'Das Kasino', 'Die Kasinos'], ['2122.', 'Gasp', 'Das Keuchen', '-'], ['2352.', 'Giggle', 'Das Kichern', '-'], ['28.', 'Child', 'Das Kind', 'Die Kinder'], ['2716.', 'Nursery', 'Das Kinderzimmer', 'Die Kinderzimmer'], ['438.', 'Chin', 'Das Kinn', 'Die Kinne'], ['663.', 'Pillow', 'Das Kissen', 'Die Kissen'], ['1682.', 'Classroom', 'Das Klassenzimmer', 'Die Klassenzimmer'], ['1139.', 'Piano', 'Das Klavier', 'Die Klaviere'], ['234.', 'Dress', 'Das Kleid', 'Die Kleider'], ['2394.', 'Garment', 'Das Kleidungsstück', 'Die Kleidungsstücke'], ['1766.', 'Infant', 'Das Kleinkind', 'Die Kleinkinder'], ['2543.', 'Ringing', 'Das Klingeln', '-'], ['1259.', 'Knock', 'Das Klopfen', '-'], ['181.', 'Knee', 'Das Knie', 'Die Knie'], ['2621.', 'Growl', 'Das Knurren', 'Die Knurren'], ['2000.', 'Cooking', 'Das Kochen', '-'], ['1806.', 'Squad', 'Das Kommando', 'Die Kommandos'], ['2769.', 'Coming', 'Das Kommen', '-'], ['2408.', 'Compliment', 'Das Kompliment', 'Die Komplimente'], ['895.', 'Account', 'Das Konto', 'Die Konten'], ['1887.', 'Concept', 'Das Konzept', 'Die Konzepte'], ['1769.', 'Concert', 'Das Konzert', 'Die Konzerte'], ['1779.', 'Grain', 'Das Korn', 'Die Körner'], ['1520.', 'Costume', 'Das Kostüm', 'Die Kostüme'], ['232.', 'Hospital', 'Das Krankenhaus', 'Die Krankenhäuser'], ['1942.', 'Herb', 'Das Kraut', 'Die Kräuter'], ['923.', 'Cross', 'Das Kreuz', 'Die Kreuze'], ['2286.', 'Cruiser', 'Das Kreuzfahrtschiff', 'Die Kreuzfahrtschiffe'], ['1955.', 'Copper', 'Das Kupfer', '-'], ['2247.', 'Kitten', 'Das Kätzchen', 'Die Kätzchen'], ['1903.', 'Kingdom', 'Das Königreich', 'Die Königreiche'], ['1981.', 'Chick', 'Das Küken', 'Die Küken'], ['765.', 'Lab', 'Das Labor', 'Die Labore'], ['2244.', 'Maze', 'Das Labyrinth', 'Die Labyrinthe'], ['519.', 'Laughter', 'Das Lachen', '-'], ['459.', 'Camp', 'Das Lager', 'Die Lager'], ['2777.', 'Loaf', 'Das Laib', 'Die Laibe'], ['1888.', 'Lamb', 'Das Lamm', 'Die Lämmer'], ['185.', 'Country', 'Das Land', 'Die Länder'], ['1789.', 'Running', 'Das Laufen', '-'], ['19.', 'Life', 'Das Leben', 'Die Leben'], ['346.', 'Creature', 'Das Lebewesen', 'Die Lebewesen'], ['431.', 'Leather', 'Das Leder', '-'], ['2174.', 'Suffering', 'Das Leiden', '-'], ['1743.', 'Linen', 'Das Leinen', '-'], ['2969.', 'Learning', 'Das Lernen', '-'], ['732.', 'Reading', 'Das Lesen', '-'], ['1036.', 'Glow', 'Das Leuchten', 'Die Leuchten'], ['474.', 'Level', 'Das Level', 'Die Level'], ['34.', 'Light', 'Das Licht', 'Die Lichter'], ['290.', 'Song', 'Das Lied', 'Die Lieder'], ['2730.', 'Praise', 'Das Lob', '-'], ['251.', 'Hole', 'Das Loch', 'Die Löcher'], ['2938.', 'Logo', 'Das Logo', 'Die Logos'], ['1390.', 'Rag', 'Das Lumpen', 'Die Lumpen'], ['92.', 'Smile', 'Das Lächeln', 'Die Lächeln'], ['488.', 'Magazine', 'Das Magazin', 'Die Magazine'], ['1243.', 'Makeup', 'Das Make-up', '-'], ['2343.', 'Management', 'Das Management', '-'], ['1890.', 'Cuff', 'Das Manschette', 'Die Manschetten'], ['2323.', 'Manuscript', 'Das Manuskript', 'Die Manuskripte'], ['803.', 'Material', 'Das Material', 'Die Materialien'], ['1949.', 'Mat', 'Das Matte', 'Die Matten'], ['339.', 'Maximum', 'Das Maximum', 'Die Maxima'], ['1521.', 'Measure', 'Das Maß', 'Die Maße'], ['568.', 'Drug', 'Das Medikament', 'Die Medikamente'], ['203.', 'Sea', 'Das Meer', 'Die Meere'], ['2688.', 'Flour', 'Das Mehl', '-'], ['1794.', 'Menu', 'Das Menü', 'Die Menüs'], ['741.', 'Feature', 'Das Merkmal', 'Die Merkmale'], ['326.', 'Knife', 'Das Messer', 'Die Messer'], ['1381.', 'Brass', 'Das Messing', '-'], ['288.', 'Metal', 'Das Metall', 'Die Metalle'], ['2112.', 'Microphone', 'Das Mikrofon', 'Die Mikrofone'], ['2910.', 'Shuffling', 'Das Mischen', 'Die Mischungen'], ['1536.', 'Sympathy', 'Das Mitgefühl', '-'], ['373.', 'Member', 'Das Mitglied', 'Die Mitglieder'], ['1474.', 'Pity', 'Das Mitleid', '-'], ['344.', 'Lunch', 'Das Mittagessen', 'Die Mittagessen'], ['838.', 'Model', 'Das Modell', 'Die Modelle'], ['1465.', 'Moonlight', 'Das Mondschein', '-'], ['777.', 'Monster', 'Das Monster', 'Die Monster'], ['1306.', 'Motel', 'Das Motel', 'Die Motels'], ['2373.', 'Motive', 'Das Motiv', 'Die Motive'], ['2256.', 'Motorcycle', 'Das Motorrad', 'Die Motorräder'], ['2273.', 'Murmur', 'Das Murmeln', '-'], ['1075.', 'Museum', 'Das Museum', 'Die Museen'], ['659.', 'Pattern', 'Das Muster', 'Die Muster'], ['22.', 'Girl', 'Das Mädchen', 'Die Mädchen'], ['749.', 'Tale', 'Das Märchen', 'Die Märchen'], ['844.', 'Furniture', 'Das Möbel', 'Die Möbel'], ['2461.', 'Nightgown', 'Das Nachthemd', 'Die Nachthemden'], ['1675.', 'Nostril', 'Das Nasenloch', 'Die Nasenlöcher'], ['2319.', 'Neon', 'Das Neon', '-'], ['1435.', 'Nest', 'Das Nest', 'Die Nester'], ['1227.', 'Net', 'Das Netz', 'Die Netze'], ['1545.', 'Network', 'Das Netzwerk', 'Die Netzwerke'], ['810.', 'Nod', 'Das Nicken', '-'], ['1173.', 'Notebook', 'Das Notizbuch', 'Die Notizbücher'], ['638.', 'Object', 'Das Objekt', 'Die Objekte'], ['133.', 'Ear', 'Das Ohr', 'Die Ohren'], ['727.', 'Victim', 'Das Opfer', 'Die Opfer'], ['1809.', 'Organ', 'Das Organ', 'Die Organe'], ['2736.', 'Easter', 'Das Ostern', '-'], ['1484.', 'Outfit', 'Das Outfit', 'Die Outfits'], ['113.', 'Couple', 'Das Paar', 'Die Paare'], ['574.', 'Pack', 'Das Pack', 'Die Packs'], ['1046.', 'Package', 'Das Paket', 'Die Pakete'], ['1030.', 'Panel', 'Das Panel', 'Die Panels'], ['90.', 'Paper', 'Das Papier', 'Die Papiere'], ['2016.', 'Paradise', 'Das Paradies', 'Die Paradiese'], ['1544.', 'Perfume', 'Das Parfüm', 'Die Parfüms'], ['500.', 'Parking', 'Das Parken', '-'], ['768.', 'Patch', 'Das Patch', 'Die Patches'], ['721.', 'Staff', 'Das Personal', '-'], ['145.', 'Horse', 'Das Pferd', 'Die Pferde'], ['787.', 'Pound', 'Das Pfund', 'Die Pfunde'], ['2948.', 'Phenomenon', 'Das Phänomen', 'Die Phänomene'], ['1780.', 'Picnic', 'Das Picknick', 'Die Picknicks'], ['352.', 'Plastic', 'Das Plastik', '-'], ['2904.', 'Plus', 'Das Plus', '-'], ['2907.', 'Podium', 'Das Podium', 'Die Podien'], ['2119.', 'Pony', 'Das Pony', 'Die Ponys'], ['1517.', 'Portrait', 'Das Porträt', 'Die Porträts'], ['1191.', 'China', 'Das Porzellan', '-'], ['1500.', 'Poster', 'Das Poster', 'Die Poster'], ['1979.', 'Principle', 'Das Prinzip', 'Die Prinzipien'], ['2483.', 'Privilege', 'Das Privileg', 'Die Privilegien'], ['112.', 'Problem', 'Das Problem', 'Die Probleme'], ['1491.', 'Product', 'Das Produkt', 'Die Produkte'], ['1812.', 'Profile', 'Das Profil', 'Die Profile'], ['651.', 'Program', 'Das Programm', 'Die Programme'], ['605.', 'Project', 'Das Projekt', 'Die Projekte'], ['675.', 'Audience', 'Das Publikum', '-'], ['1945.', 'Puff', 'Das Puff', 'Die Puffs'], ['1571.', 'Powder', 'Das Pulver', 'Die Pulver'], ['587.', 'Square', 'Das Quadrat', 'Die Quadrate'], ['359.', 'Wheel', 'Das Rad', 'Die Räder'], ['2504.', 'Radar', 'Das Radar', '-'], ['292.', 'Radio', 'Das Radio', 'Die Radios'], ['123.', 'Right', 'Das Recht', '-'], ['2494.', 'Talking', 'Das Reden', '-'], ['2678.', 'Refuge', 'Das Refugium', 'Die Refugien'], ['653.', 'Shelf', 'Das Regal', 'Die Regale'], ['2239.', 'Register', 'Das Register', 'Die Register'], ['1194.', 'Deer', 'Das Reh', 'Die Rehe'], ['2294.', 'Realm', 'Das Reich', 'Die Reiche'], ['2354.', 'Cleaning', 'Das Reinigen', '-'], ['1233.', 'Travel', 'Das Reisen', 'Die Reisen'], ['594.', 'Race', 'Das Rennen', 'Die Rennen'], ['2546.', 'Resort', 'Das Resort', 'Die Resorts'], ['422.', 'Restaurant', 'Das Restaurant', 'Die Restaurants'], ['2817.', 'Recipe', 'Das Rezept', 'Die Rezepte'], ['2145.', 'Beef', 'Das Rindfleisch', '-'], ['1645.', 'Cattle', 'Das Rindvieh', '-'], ['1127.', 

In [33]:
mapping = {'Der':'m', 'Die':'f', 'Das':'n'}

df = pd.DataFrame(cleansed_lines, columns=('cardinal', 'english', 'g_singular', 'g_plural'))
df['g_plural_nude'] = df['g_plural'].apply(lambda x: x[4:])
df['g_singular_nude'] = df['g_singular'].apply(lambda x: x[4:] if x[:3] in {'Der', 'Die', 'Das'} else x)
df['sex'] = df['g_singular'].apply(lambda x: mapping[x[:3]] if x[:3] in {'Der', 'Die', 'Das'} else np.nan)
df

,cardinal,english,g_singular,g_plural,g_plural_nude,g_singular_nude,sex
0,170.,Dinner,Das Abendessen,Die Abendessen,Abendessen,Abendessen,n
1,1286.,Adventure,Das Abenteuer,Die Abenteuer,Abenteuer,Abenteuer,n
2,1773.,Compartment,Das Abteil,Die Abteile,Abteile,Abteil,n
3,2086.,Badge,Das Abzeichen,Die Abzeichen,Abzeichen,Abzeichen,n
4,1698.,Shrug,Das Achselzucken,-,,Achselzucken,n
...,...,...,...,...,...,...,...
2549,2869.,Transfer,Die Überweisung,Die Überweisungen,Überweisungen,Überweisung,f
2550,2222.,Conviction,Die Überzeugung,Die Überzeugungen,Überzeugungen,Überzeugung,f
2551,627.,Practice,Die Übung,Die Übungen,Übungen,Übung,f
2552,309.,Mama,Mama,-,,Mama,NaN
2553,2918.,Upstairs,Oben,-,,Oben,NaN

In [34]:
result = df.merge(chassis, how='left', left_on=['g_singular_nude', 'sex'], right_on=['nominativ singular', 'genus'])

In [35]:
result['plural_agreement'] = result.apply(lambda x: x['nominativ plural'] == x['g_plural_nude'] or (x['nominativ plural'] is np.nan and x['g_plural_nude'] == ''), axis=1)

In [36]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(result[result['plural_agreement'] == False][['g_singular', 'g_plural_nude', 'nominativ plural']])
print(len(result[result['plural_agreement'] == False]))

                   g_singular          g_plural_nude    nominativ plural
7                   Das Alien                 Aliens                 NaN
8                   Das Alter                                      Alter
13            Das Anschwellen            Anschwellen                 NaN
17                  Das Aroma                 Aromen                 NaN
18                  Das Array                 Arrays                 NaN
24             Das Aufblitzen             Aufblitzen                 NaN
25     Das Aufeinandertreffen     Aufeinandertreffen                 NaN
32                 Das Backup                Backups                 NaN
35              Das Baldachin             Baldachine                 NaN
36                   Das Band                 Bänder                 NaN
37                   Das Band                 Bänder                 NaN
48            Das Bewusstsein                               Bewusstseine
56                   Das Blut                                      Blute
58                   Das Boot                  Boote                 NaN
59                 Das Braten                 Braten                 NaN
62                   Das Brot                                      Brote
71                  Das Chili                 Chilis                 NaN
74                  Das Corps                  Cores               Corps
78                   Das Deck                  Decks                 NaN
80                Das Denkmal              Denkmäler                 NaN
86                 Das Doppel                 Dopple              Doppel
90          Das Durcheinander                              Durcheinander
97               Das Eigentum                                  Eigentume
98             Das Einfrieren          Einfrierungen                 NaN
101                   Das Eis                    Eis                 NaN
106             Das Elfenbein                                 Elfenbeine
116              Das Erwachen               Erwachen                 NaN
117                 Das Essen                                      Essen
118             Das Esszimmer                                  Esszimmer
119               Das Etikett              Etiketten                 NaN
125               Das Fauchen                Fauchen                 NaN
127                  Das Feld                 Felder                 NaN
131              Das Festmahl              Festmahle                 NaN
135                Das Fieber                                     Fieber
136                Das Finish                 Finish             Finishs
138              Das Flackern               Flackern                 NaN
139               Das Flanell                Flanell                 NaN
142                  Das Floß                  Floße               Flöße
144              Das Flüstern                Flüster                 NaN
146                  Das Foto                  Fotos                 NaN
152                Das Futter                                     Futter
154                   Das Gas                                       Gase
159        Das Gebäudekomplex        Gebäudekomplexe                 NaN
164                Das Gehalt               Gehälter                 NaN
168                  Das Geld                                     Gelder
177                 Das Genie                 Genies                 NaN
190               Das Gesicht              Gesichter                 NaN
193              Das Getreide                                   Getreide
200                Das Gewirr                Gewirre                 NaN
206                  Das Glas                 Gläser              Glasen
207         Das Gleichgewicht                             Gleichgewichte
213                  Das Grau                                      Graus
215               Das Grollen                Grollen                 NaN
217               Das Grunzen                Grunzen                 NaN
218                  Das Grün                                      Grüns
222                Das Halten                 Halten                 NaN
232                  Das Herz                 Herzen                 NaN
234                Das Heulen              Heulungen                 NaN
235                Das Hinken                 Hinken                 NaN
236                  Das Holz                                     Hölzer
237                  Das Holz                                     Hölzer
243              Das Imperium                 Reiche            Imperien
250             Das Interesse                                 Interessen
258               Das Journal               Journale            Journals
260                 Das Juwel                Juwelen                 NaN
283               Das Knurren                Knurren                 NaN
285              Das Kommando              Kommandos                 NaN
291                  Das Korn                 Körner                 NaN
297                Das Kupfer                                     Kupfer
301                 Das Labor                 Labore                 NaN
304                 Das Lager                  Lager                 NaN
305                  Das Laib                  Laibe                 NaN
307                  Das Land                 Länder                 NaN
311                 Das Leder                                      Leder
312                Das Leiden                                     Leiden
313                Das Leinen                                     Leinen
316              Das Leuchten               Leuchten                 NaN
317                 Das Level                  Level                 NaN
318                 Das Licht                Lichter                 NaN
320                   Das Lob                                       Lobe
322                  Das Logo                  Logos                 NaN
323                Das Lumpen                 Lumpen                 NaN
326               Das Make-up                                   Make-ups
327            Das Management                                Managements
328            Das Manschette            Manschetten                 NaN
331                 Das Matte                 Matten                 NaN
336                  Das Mehl                                      Mehle
343               Das Mischen             Mischungen                 NaN
359                 Das Möbel                  Möbel                 NaN
372                Das Ostern                                     Ostern
375                  Das Pack                  Packs                 NaN
378                 Das Panel                 Panels                 NaN
383                 Das Patch                Patches                 NaN
388              Das Picknick              Picknicks                 NaN
393               Das Porträt               Porträts                 NaN
394             Das Porzellan                                 Porzellane
395                Das Poster                 Poster                 NaN
396               Das Prinzip             Prinzipien                 NaN
397              Das Privileg            Privilegien                 NaN
403              Das Publikum                                    Publika
404                  Das Puff                  Puffs                 NaN
408                   Das Rad                  Räder                 Rad
410                 Das Radio                 Radios                 NaN
411                 Das Recht                                     Rechte
414                 Das Regal                 Regale                 NaN
419                Das Reisen                 Reisen                 NaN
425              Das Rindvieh                                Rindviecher
426                Das Risiko                Risiken                 NaN
427                Das Ritual                Rituale                 NaN
429                  Das Salz                                      Salze
430              Das Sandwich             Sandwiches                 NaN
431                Das Schach                                    Schachs
435                Das Schema               Schemata                 NaN
436             Das Schicksal                                 Schicksale
437              Das Schießen                                   Schießen
446          Das Schrotflinte          Schrotflinten                 NaN
457                   Das Set                   Sets                 NaN
458               Das Shuttle                Shuttle                 NaN
464                Das Skript                Skripte                 NaN
471                 Das Spray                 Sprays                 NaN
473              Das Spritzen               Spritzen                 NaN
474               Das Spucken                Spucken                 NaN
481               Das Stöhnen                 Stöhne                 NaN
486              Das Szenario              Szenarien                 NaN
488               Das Tablett               Tabletts                 NaN
496                Das Tattoo                Tattoos                 NaN
497                  Das Taxi                  Taxis                 NaN
503                 Das Tempo                                     Tempos
505              Das Tentakel               Tentakel                 NaN
508                 Das Thema                 Themen                 NaN
510                Das Timing               Timingen             Timings
518                  Das Tuch                 Tücher                 NaN
520               Das Unkraut                                  Unkräuter
522          Das Urheberrecht                              Urheberrechte
524                Das Vakuum                  Vakua                 NaN
529             Das Verhalten                                  Verhalten
530             Das Verlangen                                  Verlangen
531              Das Versagen               Versagen                 NaN
535           Das Verständnis                              Verständnisse
536             Das Vertrauen              Vertrauen                 NaN
538               Das Viertel                Viertel                 NaN
539                 Das Virus                  Viren                 NaN
540                  Das Volk                                     Völker
541               Das Volumen               Volumina                 NaN
542           Das Vorbeigehen            Vorbeigehen                 NaN
543                 Das Wachs                                     Wachse
549                Das Weinen                 Weinen                 NaN
553                Das Wetter                                     Wetter
555                  Das Witz                  Witze                 NaN
559                  Das Wort                 Wörter               Worte
560                 Das Wrack                 Wracks                 NaN
566                  Das Zeug                                      Zeuge
570               Das Zittern                Zittern                 NaN
571               Das Zuhause                Zuhause                 NaN
572              Das Zwinkern               Zwinkern                 NaN
574                    Das Öl                                        Öle
577                Der Abfall                                    Abfälle
580              Der Abschied                                  Abschiede
585               Der Admiral               Admirale                 NaN
591                   Der Akt                   Akte               Akten
592           Der Aktenkoffer           Aktentaschen         Aktenkoffer
596               Der Alkohol                                   Alkohole
601           Der Angestellte           Angestellten                 NaN
614               Der Applaus                                   Applause
622               Der Asphalt                                   Asphalte
630              Der Aufprall              Aufprälle           Aufpralle
631               Der Aufruhr                Aufruhr            Aufruhre
638              Der Ausdruck              Ausdrücke           Ausdrucke
644              Der Autobahn             Autobahnen                 NaN
650                Der Balkon                Balkone                 NaN
653                Der Ballon                Ballons                 NaN
658            Der Basketball                                Basketbälle
662                 Der Bauer                 Bauern               Bauer
665                Der Beamte                Beamten                 NaN
667           Der Bedienstete           Bediensteten                 NaN
678                Der Besitz                                    Besitze
692                 Der Block                 Blöcke                 NaN
698                 Der Bogen                  Bögen                 NaN
709           Der Briefkasten            Briefkästen                 NaN
717                   Der Bus                  Busse                 NaN
720                Der Butler                 Diener              Butler
723                   Der Bär                  Bären                 NaN
728                Der Campus                  Campi                 NaN
729                Der Carter                 Carter                 NaN
730               Der Cartoon               Cartoons                 NaN
731            Der Champagner                                 Champagner
733                Der Charme                Charmes                 NaN
737                  Der Chor                  Chöre                 NaN
738                  Der Clan                  Clans                 NaN
742               Der Cluster                Cluster                 NaN
753                 Der Dampf                                     Dämpfe
754                  Der Dank           Danksagungen                 NaN
755                  Der Darm                                      Därme
758                 Der Dekan                                     Dekane
760               Der Delphin                Delfine            Delphine
763              Der Deutsche              Deutschen                 NaN
764                Der Diakon                Diakone                 NaN
774                Der Dollar                Dollars                 NaN
775                Der Donner                                     Donner
777                  Der Dorn                 Dornen                 NaN
780                 Der Druck                 Drücke                 NaN
781             Der Dschungel              Dschungel                 NaN
784                 Der Dunst                                     Dünste
791              Der Eidechse              Eidechsen                 NaN
798           Der Eingeborene           Eingeborenen                 NaN
799          Der Einheimische          Einheimischen                 NaN
809            Der Elternteil            Elternteile                 NaN
811   Der Empfangsmitarbeiter    Empfangsmitarbeiter                 NaN
820            Der Erwachsene            Erwachsenen                 NaN
824                 Der Faden                  Fäden                 NaN
836                  Der Fels                 Felsen                 NaN
845                 Der Fleck                Flecken                 NaN
853                 Der Fokus                   Foki             Fokusse
854           Der Fortschritt                               Fortschritte
858           Der Freiwillige           Freiwilligen                 NaN
859                Der Fremde                Fremden                 NaN
861               Der Frieden                                    Frieden
865                 Der Frost                                     Fröste
876                  Der Gast                  Gäste              Gasten
881             Der Gefangene             Gefangenen                 NaN
885                 Der Geist                Geister                 NaN
886              Der Gelehrte              Gelehrten                 NaN
888               Der General               Generäle                 NaN
891             Der Geschmack            Geschmäcker                 NaN
893         Der Geschäftsmann         Geschäftsleute                 NaN
897                   Der Gin                                       Gins
899                  Der Gips                                      Gipse
901         Der Gleichaltrige         Gleichaltrigen                 NaN
902                Der Globus                 Globen                 NaN
903                  Der Golf                                      Golfe
908                Der Granit                                    Granite
926                  Der Halt                  Halte                 NaN
931                Der Hammer                 Hämmer              Hammer
932                Der Handel                 Handel              Händel
939               Der Heilige               Heiligen                 NaN
944                Der Herbst                  Fälle             Herbste
948                Der Herzog                 Herzog             Herzöge
958               Der Holster                Holster                 NaN
959                 Der Homer                 Homers                 NaN
960                 Der Honig                                     Honige
965                 Der Humor                                     Humore
966                 Der Humor                                    Humores
969              Der Hurrikan              Hurrikane                 NaN
976                 Der Index                Indizes                 NaN
979                Der Ingwer                                     Ingwer
990                 Der Jubel                  Jubel                 NaN
991           Der Jugendliche           Jugendlichen                 NaN
992                 Der Junge                 Jungen                 NaN
998                 Der Kamin                 Kamine                 NaN
1004               Der Karton                Kartons                 NaN
1006             Der Kaugummi              Kaugummis                 NaN
1008               Der Kehren                 Kehren                 NaN
1014                 Der Kerl                  Kerle                 NaN
1016               Der Kiefer                 Kiefer                 NaN
1017                 Der Kies                                      Kiese
1019           Der Kinderbett           Kinderbetten                 NaN
1020                  Der Kip                   Kips                 Kip
1031           Der Knäckebrot            Knäckebrote                 NaN
1050               Der Kragen                 Kragen                 NaN
1051                 Der Kran                  Kräne                 NaN
1052                 Der Kran                  Kräne                 NaN
1053         Der Krankenwagen           Krankenwagen                 NaN
1055               Der Krater                 Krater             Kratere
1057                Der Krebs                                     Krebse
1066               Der Kumpel                 Kumpel                 NaN
1081               Der Laptop                Laptops                 NaN
1083            Der Lastwagen              Lastwagen                 NaN
1086             Der Lavendel                                   Lavendel
1087         Der Lebensmittel           Lebensmittel                 NaN
1091             Der Leutnant              Leutnants                 NaN
1095          Der Lieferwagen            Lieferwagen                 NaN
1100               Der Lupfer                 Lupfen              Lupfer

In [37]:
chassis.columns

Index(['lemma', 'pos', 'genus', 'genus 1', 'genus 2', 'genus 3', 'genus 4',
       'nominativ singular', 'nominativ singular*', 'nominativ singular 1',
       'nominativ singular 2', 'nominativ singular 3', 'nominativ singular 4',
       'nominativ singular stark', 'nominativ singular schwach',
       'nominativ singular gemischt', 'nominativ plural', 'nominativ plural*',
       'nominativ plural 1', 'nominativ plural 2', 'nominativ plural 3',
       'nominativ plural 4', 'nominativ plural stark',
       'nominativ plural schwach', 'nominativ plural gemischt',
       'genitiv singular', 'genitiv singular*', 'genitiv singular 1',
       'genitiv singular 2', 'genitiv singular 3', 'genitiv singular 4',
       'genitiv singular stark', 'genitiv singular schwach',
       'genitiv singular gemischt', 'genitiv plural', 'genitiv plural*',
       'genitiv plural 1', 'genitiv plural 2', 'genitiv plural 3',
       'genitiv plural 4', 'genitiv plural stark', 'genitiv plural schwach',
       'genitiv plural gemischt', 'dativ singular', 'dativ singular*',
       'dativ singular 1', 'dativ singular 2', 'dativ singular 3',
       'dativ singular 4', 'dativ singular stark', 'dativ singular schwach',
       'dativ singular gemischt', 'dativ plural', 'dativ plural*',
       'dativ plural 1', 'dativ plural 2', 'dativ plural 3', 'dativ plural 4',
       'dativ plural stark', 'dativ plural schwach', 'dativ plural gemischt',
       'akkusativ singular', 'akkusativ singular*', 'akkusativ singular 1',
       'akkusativ singular 2', 'akkusativ singular 3', 'akkusativ singular 4',
       'akkusativ singular stark', 'akkusativ singular schwach',
       'akkusativ singular gemischt', 'akkusativ plural', 'akkusativ plural*',
       'akkusativ plural 1', 'akkusativ plural 2', 'akkusativ plural 3',
       'akkusativ plural 4', 'akkusativ plural stark',
       'akkusativ plural schwach', 'akkusativ plural gemischt'],
      dtype='object')

In [47]:
chassis

,lemma,pos,genus,genus 1,genus 2,genus 3,genus 4,nominativ singular,nominativ singular*,nominativ singular 1,...,akkusativ singular gemischt,akkusativ plural,akkusativ plural*,akkusativ plural 1,akkusativ plural 2,akkusativ plural 3,akkusativ plural 4,akkusativ plural stark,akkusativ plural schwach,akkusativ plural gemischt
0,-algie,"Gebundenes Lexem,Substantiv",f,NaN,NaN,NaN,NaN,-algie,NaN,NaN,...,NaN,-algien,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-ant,"Affix,Substantiv,Suffix",NaN,m,n,NaN,NaN,NaN,NaN,-ant,...,NaN,NaN,NaN,-anten,-ante,NaN,NaN,NaN,NaN,NaN
2,-anz,"Affix,Substantiv,Suffix",f,NaN,NaN,NaN,NaN,-anz,NaN,NaN,...,NaN,-anzen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-chen,"Affix,Substantiv,Suffix",n,NaN,NaN,NaN,NaN,-chen,NaN,NaN,...,NaN,-chen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-elchen,"Affix,Substantiv,Suffix",n,NaN,NaN,NaN,NaN,-elchen,NaN,NaN,...,NaN,-elchen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102439,Ḫāriǧit,Substantiv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102440,’Ndrangheta,Substantiv,f,NaN,NaN,NaN,NaN,’Ndrangheta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102441,’Sgebengu,Substantiv,m,NaN,NaN,NaN,NaN,’Sgebengu,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102442,’s-Gravenhage,"Substantiv,Toponym",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102443,’s-Hertogenbosch,"Substantiv,Toponym",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN